# -*- coding: utf-8 -*-
"""pdf-reader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBzBMptAKp6wLmFY4OhMKEskMAQlwDL4
"""

#pip install fitz
#pip install tools
# pip install PyMuPDF

import fitz  # PyMuPDF
import re

def extract_paragraphs_by_page(pdf_path, threshold=10):

    paragraphs_by_page = {}

    try:
        with fitz.open(pdf_path) as pdf_file:
            for page_index, page in enumerate(pdf_file):

                # Извлекаем текст
                text = page.get_text("text")

                # Количество потенциальных элементов оглавления
                pattern_count = len(re.findall(r'\b\w+,\s*\d+', text))

                # Если страница похожа на оглавление - пропускаем
                if pattern_count > threshold:
                    continue

                # Разбиваем на строки, фильтруем пустые
                paragraphs = [
                    line.strip()
                    for line in text.split("\n")
                    if line.strip()
                    and not re.match(r'^\d+\w*[\s\W]+\d+$', line)
                ]

                if paragraphs:
                    paragraphs_by_page[page_index] = paragraphs

    except Exception as e:
        print(f"Ошибка: {e}")

    return paragraphs_by_page

pdf_path = "/content/monetary20250129a1.pdf"

data = extract_paragraphs_by_page(pdf_path, threshold=10)

for page, paras in data.items():
    print(f"--- Page {page} ---")
    for p in paras:
        print(p)